-- MySQL schema for Nucleus PMS Core + HRMS

CREATE DATABASE IF NOT EXISTS nucleus_pms;
USE nucleus_pms;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hotels (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  legal_name VARCHAR(200) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  email VARCHAR(120) DEFAULT NULL,
  website VARCHAR(200) DEFAULT NULL,
  address VARCHAR(300) DEFAULT NULL,
  logo_url TEXT DEFAULT NULL,
  default_currency ENUM('XOF', 'EUR') NOT NULL DEFAULT 'XOF',
  tva_rate DECIMAL(5,2) NOT NULL DEFAULT 18.00,
  tourist_tax_enabled TINYINT(1) NOT NULL DEFAULT 0,
  tourist_tax_amount INT NOT NULL DEFAULT 1000,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  description TEXT,
  default_price INT NOT NULL,
  max_capacity INT NOT NULL,
  color VARCHAR(20) DEFAULT NULL,
  icon VARCHAR(80) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS rooms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_number VARCHAR(20) NOT NULL UNIQUE,
  category_id INT NOT NULL,
  floor VARCHAR(80) NOT NULL,
  capacity INT NOT NULL,
  bed_type VARCHAR(80) NOT NULL,
  area INT NOT NULL,
  base_price INT NOT NULL,
  notes TEXT,
  active TINYINT(1) NOT NULL DEFAULT 1,
  current_status VARCHAR(50) DEFAULT NULL,
  housekeeping_status VARCHAR(50) DEFAULT NULL,
  maintenance_status VARCHAR(50) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES room_categories(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS guests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(120) NOT NULL,
  last_name VARCHAR(120) NOT NULL,
  gender ENUM('M', 'F', 'Autre') DEFAULT 'Autre',
  birth_date DATE DEFAULT NULL,
  nationality VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(60) DEFAULT NULL,
  email VARCHAR(180) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  document_type ENUM('CNI', 'Passeport', 'Permis', 'Autre') DEFAULT 'Autre',
  document_number VARCHAR(120) DEFAULT NULL,
  notes TEXT,
  vip TINYINT(1) NOT NULL DEFAULT 0,
  blacklist TINYINT(1) NOT NULL DEFAULT 0,
  guest_type ENUM('Individuel','Entreprise','Corporate') DEFAULT 'Individuel',
  company_name VARCHAR(180) DEFAULT NULL,
  tax_id VARCHAR(120) DEFAULT NULL,
  deferred_payment_authorized TINYINT(1) NOT NULL DEFAULT 0,
  payment_terms VARCHAR(120) DEFAULT NULL,
  credit_limit INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reservations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reservation_number VARCHAR(80) NOT NULL UNIQUE,
  guest_id INT NOT NULL,
  room_id INT NOT NULL,
  booking_source_id VARCHAR(120) DEFAULT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'En attente',
  arrival_date DATE NOT NULL,
  departure_date DATE NOT NULL,
  adults INT NOT NULL DEFAULT 1,
  children INT NOT NULL DEFAULT 0,
  nights INT NOT NULL DEFAULT 1,
  room_rate INT NOT NULL DEFAULT 0,
  discount INT NOT NULL DEFAULT 0,
  tax_amount INT NOT NULL DEFAULT 0,
  total_amount INT NOT NULL DEFAULT 0,
  deposit INT NOT NULL DEFAULT 0,
  balance INT NOT NULL DEFAULT 0,
  remarks TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE CASCADE,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_number VARCHAR(80) NOT NULL UNIQUE,
  reservation_id INT NOT NULL,
  guest_id INT NOT NULL,
  subtotal INT NOT NULL DEFAULT 0,
  discount INT NOT NULL DEFAULT 0,
  tax INT NOT NULL DEFAULT 0,
  total INT NOT NULL DEFAULT 0,
  paid INT NOT NULL DEFAULT 0,
  balance INT NOT NULL DEFAULT 0,
  status ENUM('Brouillon', 'Émise', 'Partiellement payée', 'Payée', 'Annulée') NOT NULL DEFAULT 'Brouillon',
  issued_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE,
  FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  item_type ENUM('Chambre','Restaurant','Minibar','Service','Supplément') NOT NULL,
  item_id VARCHAR(120) DEFAULT NULL,
  description TEXT,
  quantity INT NOT NULL DEFAULT 1,
  unit_price INT NOT NULL DEFAULT 0,
  tax INT NOT NULL DEFAULT 0,
  total INT NOT NULL DEFAULT 0,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  reservation_id INT DEFAULT NULL,
  payment_method ENUM('Espèces','Carte','Mobile Money','Virement','Chèque') NOT NULL,
  amount INT NOT NULL DEFAULT 0,
  reference VARCHAR(180) DEFAULT NULL,
  payment_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cashier_id INT DEFAULT NULL,
  status ENUM('Validé','Remboursé','Annulé') NOT NULL DEFAULT 'Validé',
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
  FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS housekeeping_tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_id INT NOT NULL,
  employee_id INT DEFAULT NULL,
  priority ENUM('Faible','Normale','Haute') NOT NULL DEFAULT 'Normale',
  status VARCHAR(50) NOT NULL DEFAULT 'À nettoyer',
  scheduled_time DATETIME DEFAULT NULL,
  completed_time DATETIME DEFAULT NULL,
  notes TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS maintenance_tickets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_id INT NOT NULL,
  category VARCHAR(120) NOT NULL,
  priority ENUM('Faible','Normale','Haute','Critique') NOT NULL DEFAULT 'Normale',
  description TEXT,
  assigned_to INT DEFAULT NULL,
  estimated_cost INT DEFAULT NULL,
  actual_cost INT DEFAULT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Signalé',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_name VARCHAR(200) NOT NULL,
  contact_name VARCHAR(120) DEFAULT NULL,
  phone VARCHAR(80) DEFAULT NULL,
  email VARCHAR(180) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(120) NOT NULL UNIQUE,
  barcode VARCHAR(120) DEFAULT NULL,
  name VARCHAR(200) NOT NULL,
  category_id INT DEFAULT NULL,
  supplier_id INT DEFAULT NULL,
  purchase_price INT NOT NULL DEFAULT 0,
  selling_price INT NOT NULL DEFAULT 0,
  unit VARCHAR(60) NOT NULL DEFAULT 'unité',
  minimum_stock INT NOT NULL DEFAULT 0,
  current_stock INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS stock_movements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  item_id INT NOT NULL,
  item_name VARCHAR(200) NOT NULL,
  sku VARCHAR(120) DEFAULT NULL,
  quantity INT NOT NULL DEFAULT 0,
  from_location VARCHAR(255) DEFAULT NULL,
  to_location VARCHAR(255) DEFAULT NULL,
  staff_name VARCHAR(180) DEFAULT NULL,
  type VARCHAR(120) DEFAULT NULL,
  FOREIGN KEY (item_id) REFERENCES stock_items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS menu_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category_id INT DEFAULT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  selling_price INT NOT NULL DEFAULT 0,
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  available TINYINT(1) NOT NULL DEFAULT 1,
  image VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restaurant_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(120) NOT NULL UNIQUE,
  reservation_id INT DEFAULT NULL,
  guest_id INT DEFAULT NULL,
  room_id INT DEFAULT NULL,
  status ENUM('En attente','En préparation','Servie','Facturée','Annulée') NOT NULL DEFAULT 'En attente',
  subtotal INT NOT NULL DEFAULT 0,
  tax INT NOT NULL DEFAULT 0,
  total INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE SET NULL,
  FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE SET NULL,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS restaurant_order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  menu_item_id INT DEFAULT NULL,
  quantity INT NOT NULL DEFAULT 1,
  unit_price INT NOT NULL DEFAULT 0,
  total INT NOT NULL DEFAULT 0,
  FOREIGN KEY (order_id) REFERENCES restaurant_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hrms_departments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  code VARCHAR(60) DEFAULT NULL,
  cost_center_code VARCHAR(80) DEFAULT NULL,
  manager_id INT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hrms_jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  department_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  salary_min INT NOT NULL DEFAULT 0,
  salary_max INT NOT NULL DEFAULT 0,
  hourly_cost INT NOT NULL DEFAULT 0,
  FOREIGN KEY (department_id) REFERENCES hrms_departments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hrms_employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  first_name VARCHAR(120) NOT NULL,
  last_name VARCHAR(120) NOT NULL,
  email VARCHAR(180) DEFAULT NULL,
  phone VARCHAR(80) DEFAULT NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'active',
  job_id INT DEFAULT NULL,
  team_id INT DEFAULT NULL,
  department_id INT DEFAULT NULL,
  hire_date DATE DEFAULT NULL,
  termination_date DATE DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES hrms_jobs(id) ON DELETE SET NULL,
  FOREIGN KEY (department_id) REFERENCES hrms_departments(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS hrms_teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  department_id INT DEFAULT NULL,
  manager_id INT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (department_id) REFERENCES hrms_departments(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS hrms_contracts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  employee_id INT NOT NULL,
  contract_type VARCHAR(80) NOT NULL,
  base_salary INT NOT NULL DEFAULT 0,
  currency ENUM('XOF','EUR') NOT NULL DEFAULT 'XOF',
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES hrms_employees(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hrms_skills (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hrms_employee_skills (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_id INT NOT NULL,
  skill_id INT NOT NULL,
  proficiency VARCHAR(120) DEFAULT NULL,
  acquired_at DATE DEFAULT NULL,
  FOREIGN KEY (employee_id) REFERENCES hrms_employees(id) ON DELETE CASCADE,
  FOREIGN KEY (skill_id) REFERENCES hrms_skills(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hrms_documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  employee_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  file_name VARCHAR(255) DEFAULT NULL,
  file_url TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES hrms_employees(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hrms_onboarding_tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  employee_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'pending',
  due_date DATE DEFAULT NULL,
  completed_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES hrms_employees(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hrms_business_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  event_type VARCHAR(120) NOT NULL,
  actor_name VARCHAR(180) NOT NULL,
  description TEXT NOT NULL,
  payload JSON DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS hrms_payroll_rules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hotel_id INT NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT DEFAULT NULL,
  rule JSON DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
